### ISSUE TITLE
Frame Rotated

### ISSUE THREAD

**Issue by droneboxid** [cuitaixiang/LOAM_NOTED#1]
Hi can you let me know the frame rotated ??

![image](https://user-images.githubusercontent.com/37235398/40127231-c42cd694-58e3-11e8-88f2-612a26dbc981.png)

**Comment by cuitaixiang** [comment]
Hi,you can see or select the frame in the global options.And your lidar coordinate system seems to be skewed and need to be calibrated.

**Comment by droneboxid** [comment]
hi can you let me know how to calibrated?

**Comment by cuitaixiang** [comment]
It doesn't matter if you have only one sensor.If you have other sensors, like camera,here is a good method:[...](https://github.com/ankitdhall/lidar_camera_calibration).
