### ISSUE TITLE
计算激光点的水平旋转角（ori）中的halfpassed

### ISSUE THREAD

**Issue by Li-Shang** [cuitaixiang/LOAM_NOTED#6]
halfpassed代表lidar扫描线是否旋转过半。但是点云中点的顺序并不是按时间读进来的啊。是否应该对每一条激光扫描线设置一个halfpassed变量呢。

**Comment by cuitaixiang** [comment]
好久都不从事相关方向了，基本都忘了，我记得是16线同时旋转，数据差不多是按旋转先后读进来的吧，halfpassed好像不那么重要，只是选择一个参照计算点而已，你自己研究一下了
